import {
  IsString,
  IsNotEmpty,
  IsNumberString,
  IsUUID,
  Length,
} from 'class-validator';

export class LoadWalletDto {
  @IsUUID()
  @IsNotEmpty()
  walletId: string;

  @IsUUID()
  @IsNotEmpty()
  cardId: string;

  @IsNumberString()
  @IsNotEmpty()
  amount: string;

  @IsString()
  @Length(6, 6) // Assuming a 4-digit transaction PIN
  @IsNotEmpty()
  pin: string;

  /**
   * Unique key generated by the client (UUID v4).
   * Prevents double charging if the network retries the request.
   */
  @IsString()
  @IsNotEmpty()
  idempotencyKey: string;
}
