export enum KycTier {
  NONE = 'NONE',
  SOFT_PENDING = 'SOFT_PENDING',
  SOFT_APPROVED = 'SOFT_APPROVED',
  HARD_PENDING = 'HARD_PENDING',
  HARD_APPROVED = 'HARD_APPROVED',
  HARD_REJECTED = 'HARD_REJECTED',
}

export enum KycDocumentType {
  NATIONAL_ID = 'NATIONAL_ID',
  PASSPORT = 'PASSPORT',
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  UTILITY_BILL = 'UTILITY_BILL', // address proof
  SELFIE = 'SELFIE',
}

export enum KycRejectionReason {
  DOCUMENT_UNCLEAR = 'DOCUMENT_UNCLEAR',
  DOCUMENT_EXPIRED = 'DOCUMENT_EXPIRED',
  NAME_MISMATCH = 'NAME_MISMATCH',
  DUPLICATE_ACCOUNT = 'DUPLICATE_ACCOUNT',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  OTHER = 'OTHER',
}
